steps:
  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/marketing-saas-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/marketing-saas-backend:latest'
      - './backend'
    id: 'build-backend'

  # Build frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/marketing-saas-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/marketing-saas-frontend:latest'
      - './frontend'
    id: 'build-frontend'

  # Push backend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/marketing-saas-backend:$COMMIT_SHA'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push frontend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/marketing-saas-frontend:$COMMIT_SHA'
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'marketing-saas-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/marketing-saas-backend:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'marketing-saas-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/marketing-saas-frontend:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
    id: 'deploy-frontend'
    waitFor: ['push-frontend', 'deploy-backend']

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/marketing-saas-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/marketing-saas-backend:latest'
  - 'gcr.io/$PROJECT_ID/marketing-saas-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/marketing-saas-frontend:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  disk_size_gb: 100
  
timeout: '1200s'
