version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: base
    container_name: marketing-saas-backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=dev-secret-change-in-production
      - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
      - VERTEX_AI_LOCATION=us-central1
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./service-account-key.json:/app/service-account-key.json:ro
    command: pnpm run dev
    networks:
      - marketing-network
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: base
    container_name: marketing-saas-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080/api
      - VITE_APP_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: pnpm run dev
    networks:
      - marketing-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: marketing-saas-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - marketing-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: marketing-saas-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - marketing-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  marketing-network:
    driver: bridge
